### ISSUE TITLE
Error with multiple columns in tabs

### ISSUE THREAD

**Issue by seehat** [johannschopplich/kirby-minimap#6]
Kirby Version: 4.7.2
Plugin Version: 1.2.2

The contents of the minimap showed up before version 1.1.0, not anymore, when introducing columns. 

Working blueprint, when I am on the content tab:
```yaml
title: Layout
tabs:
  content:
    label: tab.content.label
    icon: text
    sections:
      fields:
        type: fields
        fields:
          blocks: fields/blocks
      children:
        label: section.children.label
        type: pages
        template: layout
  seo:
    label: tab.content.label
    icon: text
    columns:
      main:
        width: 3/4
        type: fields
        fields:
      sidebar:
        width: 1/4
        sections:
```

Not working anymore and gives the error, see further down:
```yaml
tabs:
  content:
    label: tab.content.label
    icon: text
    columns:
      main:
        width: 3/4
        type: fields
        fields:
          blocks: fields/blocks
      sidebar:
        width: 1/4
        sections:
          children:
            label: section.children.label
            type: pages
            template: layout
  seo:
    label: tab.content.label
    icon: text
    columns:
      maind:
        width: 3/4
        type: fields
        fields:
      sidebard:
        width: 1/4
        sections:
```

Now I get the following error in the console: 

```javascript
index.min.js:2 TypeError: t.view.props.tab.columns is not iterable
    at N (index.js?1747736950:215:6674)
    at L (index.js?1747736950:215:5547)
    at async O.immediate (index.js?1747736950:215:5012)
```

Do you have an idea why? 

I love the idea of this plugin.
